# Generated by Django 2.1.3 on 2018-12-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_address', '0005_auto_20170418_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleRegion',
        ),
    ]
